--select * from customer limit 20
--Q1 WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUTOMERS?

select gender, sum(purchase_amount) as revenue
from customer 
group by gender

--q2 which customers used a discount but still spent more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and
purchase_amount >= (select avg(purchase_amount) from customer)

--q3 which are the top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--q4 compare the average purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


--q5 do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount),
sum(purchase_amount) 
from customer
group by subscription_status

--q6 which 5 products have the higest percentage of purchases with discounts applied
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--q7 segment customers into new, returning and loyal based on their
--number of previous purchases and show the count of each segment

with customer_type as(
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment

--q8 what are the top 3 most purchased products within each category
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3

 

